services:
  sql_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mssql_container
    ports:
      - '${APP_PORT:-1433}:1433'
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=${ACCEPT_EULA}